### ISSUE TITLE
Traduceri

### ISSUE THREAD

**Issue by hodorogandrei** [infoeducatie/gazeta#23]
Trebuie traduse textele (pagina de 404, search, categories, etc.)
- [x] 404 page
- [x] search
- [x] categories 
- [x] `Follow`
- [x] `More`
- [x] `Next`
- [x] `Previous`

**Comment by robertdxyz** [comment]
Ar trebui creat un fisier de traduceri nu modificat direct in cod

**Comment by hodorogandrei** [comment]
Will try
