### ISSUE TITLE
Pagina de contributori

### ISSUE THREAD

**Issue by hodorogandrei** [infoeducatie/gazeta#24]
Trebuie rezolvata pagina de contributori (acelasi plugin?)

**Comment by robertdxyz** [comment]
Nu este prea bine scris. Testeaza cu altele pe local si daca gasesti unul mai bun scrie aici

**Comment by vtemian** [comment]
Am instalat `Team-Manager` https://github.com/infoeducatie/gazeta/commit/ac5497f669cc2fd25794b6622ce2b21cb02f86bc  si cred ca arata cat de cat decent. Cu putin CSS, chiar ar merge.
http://gazeta.info.ro/contributori/

Feedback?

**Comment by robertdxyz** [comment]
Nu imi place ca sunt inegale alea si e greu sa le faci sa fie egale. Celalalt era fain ca doar maouse hover aparea text.

**Comment by vtemian** [comment]
Sincer, as renunta la text

**Comment by robertdxyz** [comment]
De acord
