### ISSUE TITLE
Facebook & twitter for articles

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/gazeta#33]
Buton de like, share si tweet pentru articole. Trebuie folosite API-urile native.

Implementarea pentru tema veche https://github.com/infoeducatie/gazeta/pull/3

**Comment by hodorogandrei** [comment]
Poti fi putin mai descriptiv, te rog?

**Comment by robertdxyz** [comment]
Buton de like, share si tweet pentru articole. Trebuie folosite API-urile native.
