### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by hodorogandrei** [infoeducatie/gazeta#49]
ginfo.ro does not redirect (anymore) to gazeta.info.ro - important aspect for SEO (139 backlinks to ginfo.ro).
- trebuie implementat 301 redirect

**Comment by csoroiu** [comment]
Cred ca e important sa rezolvam si partea asta.
Din cate imi dau seama e vb doar de o instructiune redirect intr-un .htaccess file, ne impiedica ceva sa rezolvam asta sau cum pot sa il rezolv eu?

**Comment by hodorogandrei** [comment]
Pai trebuie sa rezolve cine are acces la domeniul ginfo.ro, fie din panoul de administrare DNS de la rotld, fie pointat domeniul pe un server de pe care se face acea redirectare din fisierul .htaccess. Ar fi de citit si asta: http://www.inboundnow.com/how-to-properly-set-up-wordpress-301-redirects/

**Comment by csoroiu** [comment]
Multumesc
